# Generated by Django 4.2.1 on 2023-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_tableresto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_cashier',
            new_name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_kitchen',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_waiterss',
        ),
    ]
