# Generated by Django 4.2.1 on 2023-05-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0004_topic_delete_tableresto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='capacity',
        ),
    ]
