# Generated by Django 4.2.1 on 2023-05-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0005_rename_code_topic_code_rename_name_topic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_code', models.CharField(max_length=30)),
                ('Category_name', models.CharField(max_length=200)),
                ('Category_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lesson_code', models.CharField(max_length=20)),
                ('Lesson_name', models.CharField(max_length=100)),
                ('Lesson_description', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
