# Generated by Django 4.2.1 on 2023-05-12 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0008_rename_lesson_name_subjudul_lesson_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessondetail_name', models.CharField(max_length=100)),
                ('isi', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Category_description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='Lesson_description',
            new_name='cesson_description',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='Lesson_name',
            new_name='lesson_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Category_code',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Category_name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='Lesson_code',
        ),
        migrations.AddField(
            model_name='lesson',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_name_lesson', to='learning_app.category'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_lesson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SubJudul',
        ),
        migrations.AddField(
            model_name='lessondetail',
            name='lesson_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.lesson'),
        ),
        migrations.AddField(
            model_name='lessondetail',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_lesson_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='Kosong', max_length=200),
        ),
    ]
